import createClient, { type Client, type Middleware } from 'openapi-fetch';
import type { paths } from './schema';

/**
 * Typed API client (root CLAUDE.md §2 — REST+OpenAPI→generated TS client, no FE/BE type drift).
 * `paths` is generated by `openapi-typescript` from the OpenAPI document the api emits from its Zod
 * DTOs (`pnpm openapi`). Callers use `client.GET('/path', { params })` / `client.POST(...)` — the
 * method, path, params, body, and response are all type-checked against the spec. Never hand-roll
 * `fetch` against the API; add the endpoint to the api's openapi registry and regenerate instead.
 */
export type ApiClient = Client<paths>;

/**
 * Create a client bound to `baseUrl` (which already includes the `/api` global prefix). When
 * `getToken` is supplied, every request gets a `Bearer` Authorization header from it.
 */
export function createApiClient(baseUrl: string, getToken?: () => string | null): ApiClient {
  const client = createClient<paths>({ baseUrl });
  if (getToken) {
    const auth: Middleware = {
      onRequest({ request }) {
        const token = getToken();
        if (token) request.headers.set('Authorization', `Bearer ${token}`);
        return request;
      },
    };
    client.use(auth);
  }
  return client;
}
